### ISSUE TITLE
Unable to build the QT applet

### ISSUE THREAD

**Issue by BenjaminSchubert** [dkopecek/usbguard#184]
I've been trying to build manually the QT applet for development.

However I stumbled upon multiple errors. I would need help on this : 

Steps to reproduce : 

- git clone https://github.com/dkopecek/usbguard
- cd usbguard/srv/GUI.QT
- qmake-qt5
- make

I get the following errors (clearing them makes me go to the next step) :

- icon.qrc is not found => remove the line in QtApplet.pro
- Cannot find <Rule.hpp> => adding `INCLUDEPATH += $$PWD/../Library` in QtApplet.pro fixes it
- cannot find "MainWindow.ui.h". This one bugs me, as I have ui_MainWindow.h available in the path ... maybe change ? If so I get : 
- cannot find "DeviceDialog.ui.h" not found, as above
- `build-config.h` not found which I cannot even find in the whole repo.

Could someone help me with this ? I did not submit a PR for the first problems as I'm not sure they are the best fixes.

Thank you !

**Comment by dkopecek** [comment]
> I get the following errors (clearing them makes me go to the next step) :

Many of these errors stem from the fact that the missing files are generated at build time by the configure and Makefile scripts, see my inline comments. Also, the QtApplet.pro file should not be there as I don't maintain it anymore...

>     icon.qrc is not found => remove the line in QtApplet.pro

Generated here: https://github.com/dkopecek/usbguard/blob/master/Makefile.am#L614

>     cannot find "MainWindow.ui.h". This one bugs me, as I have ui_MainWindow.h available in the path ... maybe change ? If so I get :
>     cannot find "DeviceDialog.ui.h" not found, as above

Unfortunately, the Qt tools (AFAIK) doesn't allow to specify how the generated files should be named. And since the automake based build system doesn't use qmake to generate these files, the file names are different. If the files had ui_ prefix, I would not be able to write the Makefile patterns and correctly handle the various qt-related file generation. The files .ui.h are generate here:

https://github.com/dkopecek/usbguard/blob/master/Makefile.am#L599

>     build-config.h not found which I cannot even find in the whole repo.

This one is generated by the configure script:

https://github.com/dkopecek/usbguard/blob/master/configure.ac#L6

I think you can safely ignore it during the development time unless you depend on results of some of the configure script checks.

**Comment by BenjaminSchubert** [comment]
Oh ok, so the .pro should be removed and the configure used right ? This makes sense, thanks !

**Comment by dkopecek** [comment]
> Oh ok, so the .pro should be removed and the configure used right ? This makes sense, thanks !

Yes, I'll take care of removing it as I'm currently doing some code cleanups.

**Comment by dkopecek** [comment]
The file was removed, closing.
