### ISSUE TITLE
Ship a change log

### ISSUE THREAD

**Issue by murinicanor** [dkopecek/usbguard#93]
hi,

it would be great if the release archives contained a CHANGELOG file. i was researching possibilities of generating that from the github release notes, but nothing useful came up. i know its probably cumbersome to take care of two places containing changes, but if you agree that it should be part of the released archives, i'd happy to create an initial file.

**Comment by dkopecek** [comment]
Hello.

Yes, I agree. Maybe I'll teach myself to keep the git history clean so that it's useful as a changelog by itself. I think that the current form of the release tags is stable now. That should help with doing diffs between consecutive releases.

It would be nice to have at least some level of automation w.r.t. changelog, i.e. maybe some script that helps to generate some raw form of the changelog from the git history which will then be reviewed and transformed into new entries in the shipped changelog.

Feel free to create the initial version. Thanks!

**Comment by murinicanor** [comment]
the changelog is not included in the released archive ;)
(i'm don't know how that archive is created, otherwise i'd create a patch ;))

**Comment by dkopecek** [comment]
Oh crap... I'll try to fix that. Thanks!

**Comment by dkopecek** [comment]
Should be fixed now. I did a forced update of the tags and updated the files in the release. Sorry, for the inconvenience!
